<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MoreStandsForShops</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
    <OutputType>Library</OutputType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Source_OLD\**\*.cs" />
    <Compile Remove="dist\**\*.cs" />
    <Compile Remove="Tests\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <!-- BepInEx and Harmony from BepInEx/core -->
    <Reference Include="BepInEx">
      <HintPath>$(BepInExCorePath)\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExCorePath)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <!-- Unity assemblies -->
    <Reference Include="UnityEngine">
      <HintPath>$(GameManagedPath)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameManagedPath)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(GameManagedPath)\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>$(GameManagedPath)\UnityEngine.ParticleSystemModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(GameManagedPath)\UnityEngine.AudioModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GameManagedPath)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(GameManagedPath)\UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <!-- Game assemblies -->
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameManagedPath)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <!-- Photon assemblies -->
    <Reference Include="Photon3Unity3D">
      <HintPath>$(GameManagedPath)\Photon3Unity3D.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="PhotonUnityNetworking">
      <HintPath>$(GameManagedPath)\PhotonUnityNetworking.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="PhotonRealtime">
      <HintPath>$(GameManagedPath)\PhotonRealtime.dll</HintPath>
      <Private>false</Private>
    </Reference>

  </ItemGroup>
</Project>
